# iterate over location list and run tasks for creating folders
- include_tasks: www-home.yml
  vars:
    location: "{{ item }}"
  loop: "{{ locations }}"

# creates the nginx base config
- name: create base NGiNX config
  ansible.builtin.template:
    src: nginx-base.conf.j2
    dest: "{{ path_nginx_config }}{{ filename_nginx_config }}"
    owner: www-data
    group: www-data
    mode: '0644'

# adds the location entries to the base config
- name: insert NGiNX location entries
  blockinfile:
    path: "{{ path_nginx_config }}{{ filename_nginx_config }}"
    insertafter: "### ANSIBLE GENERATED ###"
    marker: "# {mark} {{ item }} #"
    block: |
      {{ lookup('template', 'nginx-location.conf.j2') }}
  loop: "{{ locations }}"
  notify: restart NGiNX