---
- name: create www-home directory for location {{ location }}
  ansible.builtin.file:
    path: "{{ path_www_home }}{{ location }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
- name: create the index.html from th template file
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ path_www_home }}{{ location }}/index.html"
    owner: www-data
    group: www-data
    mode: '0644'