---
### validate zip code w/regex
- name: validate zip code
  fail:
    msg: "parameter not a valid zip code => {{ zip_code }}"
  when: zip_code is not regex("^[0-9]{5}$")

### call rest service with zip code
- name: call rest service
  uri:
    url: "{{ url }}{{ zip_code }}"
    return_content: yes
  register: json_response

### get json part from response
- name: get json
  set_fact:
    json_content: "{{ json_response.content | from_json }}"

### check for the json tag and print debug message if tag is present
- name: validate reponse
  fail:
    msg: "no city found for zip code => {{ zip_code }}"
  when: json_content.records.0.fields.plz_name is not defined

- name: print city name
  debug:
    msg: "city => {{  json_content.records.0.fields.plz_name }}"