---
# loop through file contents and install listed packages
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ lookup('file', 'package_requirements.txt').splitlines() }}"